In [4]:
#  ! ==> Terminal
!pip list -v

Package                           Version      Location                                   Installer
--------------------------------- ------------ ------------------------------------------ ---------
aiobotocore                       2.7.0        C:\ProgramData\anaconda3\Lib\site-packages conda
aiohttp                           3.9.3        C:\ProgramData\anaconda3\Lib\site-packages conda
aioitertools                      0.7.1        C:\ProgramData\anaconda3\Lib\site-packages conda
numpy                             1.26.4       C:\ProgramData\anaconda3\Lib\site-packages conda
numpydoc                          1.5.0        C:\ProgramData\anaconda3\Lib\site-packages conda
openpyxl                          3.0.10       C:\ProgramData\anaconda3\Lib\site-packages
overrides                         7.4.0        C:\ProgramData\anaconda3\Lib\site-packages conda
packaging                         23.1         C:\ProgramData\anaconda3\Lib\site-packages conda
pandas                            2.1.

In [ ]:
!pip install numpy

In [6]:
import numpy as np
np.absolute(-3)

3

In [21]:
first = np.array([8.99999, .2, .3], dtype=int)
l1 = [1, 2, 3]
np.array(l1)
print(type(first), first)
print(type(l1), l1)

<class 'numpy.ndarray'> [8 0 0]
<class 'list'> [1, 2, 3]


In [32]:
import time
import numpy as np

def add_lists(a, b):
    result = []
    for i in range(min(len(a), len(b))):
        result.append(a[i] + b[i])
    return result

def add_numpy(a, b):
    result = a + b

########## create
n = 10 ** 7
a_list = list(range(n))
b_list = list(range(n))

np_a = np.array(a_list)
np_b = np.array(b_list)

########## measure list

start = time.time()

add_lists(a_list, b_list)

end = time.time()
print(f"it took {end - start:.6f} seconds")

########## measure numpy

start = time.time()

add_numpy(np_a, np_b)

end = time.time()
print(f"it took {end - start:.6f} seconds")



it took 2.816803 seconds
it took 0.044660 seconds


In [33]:
import sys
import numpy as np

# Number of elements
n = 1_000_000

# Create a Python list and a NumPy array with the same integers
py_list = list(range(n))
np_array = np.arange(n)

# Calculate the size of the Python list container itself (a list of pointers)
list_container_size = sys.getsizeof(py_list)

# Calculate the size of each integer element in the list
list_elements_size = sum(sys.getsizeof(item) for item in py_list)
total_py_list_size = list_container_size + list_elements_size

# For the NumPy array, use the nbytes attribute to get the size of the data buffer
np_array_size = np_array.nbytes

print("Python list container size:", list_container_size, "bytes")
print("Python list total size (including all integer objects):", total_py_list_size, "bytes")
print("NumPy array size (nbytes):", np_array_size, "bytes")


Python list container size: 8000056 bytes
Python list total size (including all integer objects): 36000056 bytes
NumPy array size (nbytes): 4000000 bytes


In [43]:
np.arange(0, 10 + 1, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [40]:
print(np.array([1, 2, 3]))
print(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(np.zeros(10, dtype=int))
print(np.zeros(10, dtype=float))
print(np.zeros((2, 5), dtype=float))
sh = np.arange(0, 10)
np.reshape(sh, (5, 2))  # change size to 5 rows and 2 columns

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
print(np.linspace(0, 10, 3, dtype=int))  # 3rd parameter = how many numbers
print(np.linspace(0, 10, 5, dtype=float))
print(np.linspace(0, 10, 6, dtype=float))
#   0             10 
#   | _ X _ X ... |

# help with colors
# ?np.linspace

[ 0  5 10]
[ 0.   2.5  5.   7.5 10. ]
[ 0.  2.  4.  6.  8. 10.]


In [93]:
randy = np.random.rand(4, 5) * 9
print(randy)
print(np.round(randy, 2))
print(randy.astype(int))


[[0.9041304  0.72530724 2.55834123 4.0090151  5.39869398]
 [5.01134905 6.72295099 8.45884558 1.94435857 1.95740763]
 [4.96931267 6.61758432 5.95005546 4.83802011 7.56149164]
 [2.86446363 4.80905159 5.63818236 0.03428061 3.05815099]]
[[0.9  0.73 2.56 4.01 5.4 ]
 [5.01 6.72 8.46 1.94 1.96]
 [4.97 6.62 5.95 4.84 7.56]
 [2.86 4.81 5.64 0.03 3.06]]
[[0 0 2 4 5]
 [5 6 8 1 1]
 [4 6 5 4 7]
 [2 4 5 0 3]]


In [99]:
# 5 random numbers 1-10
# 9, 8, f()
# 9, 7, 5, 4, 6

np.random.seed(42)
np.random.randint(0, 101, (2,5))



array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]])